server:
  port: 9000


spring:
  jackson:
    serialization:
      indent-output: true
  cloud:
    function:
      definition: receiver
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        receiver-in-0:
          destination: publisher



  datasource:
    url: jdbc:postgresql://localhost:5435/bpm
    username: bpm
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

security:
  authentication:
    jwt:
      secret: eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0VFb0qJ1LRg4ujbZoRMXnVkUgiuKq5KxWqNdbKqG9VvzS1zZa9LPxtHWKa64zDl2ofkT8F6jBtK4riUfPg
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 604800

